export function generateHtmlReport(markdown: string, mode: string, paths: string[]): string {
  const issues = parseIssues(markdown)
  const summary = parseSummary(markdown)

  const severityColors: Record<string, string> = {
    'CRITICAL': '#E74C3C', 'HIGH': '#E67E22', 'MEDIUM': '#F39C12', 'LOW': '#3498DB',
    '🔴': '#E74C3C', '🟠': '#E67E22', '🟡': '#F39C12', '🔵': '#3498DB',
  }

  const issueCards = issues.map((issue, i) => {
    const color = severityColors[issue.severity.replace(/[🔴🟠🟡🔵]/g, '')] || severityColors[issue.severity.slice(0, 2)] || '#666'
    return `
    <div class="issue-card">
      <div class="issue-head">
        <span class="issue-severity" style="background:${color}">${issue.severity}</span>
        <span class="issue-title">${escapeHtml(issue.title)}</span>
      </div>
      ${issue.line ? `<div class="issue-meta">📄 ${escapeHtml(issue.file || '')} · 📍 行 ${escapeHtml(issue.line)}</div>` : ''}
      ${issue.problem ? `<div class="issue-section"><strong>问题：</strong>${escapeHtml(issue.problem)}</div>` : ''}
      ${issue.fix ? `<div class="issue-section"><strong>修复：</strong>${escapeHtml(issue.fix)}</div>` : ''}
      ${issue.code ? `<pre class="issue-code">${escapeHtml(issue.code)}</pre>` : ''}
    </div>`
  }).join('\n')

  const total = summary.total || issues.length
  const critical = summary.critical || issues.filter((i) => i.severity.includes('CRITICAL') || i.severity.includes('🔴')).length
  const high = summary.high || issues.filter((i) => i.severity.includes('HIGH') || i.severity.includes('🟠')).length
  const medium = summary.medium || issues.filter((i) => i.severity.includes('MEDIUM') || i.severity.includes('🟡')).length
  const low = summary.low || issues.filter((i) => i.severity.includes('LOW') || i.severity.includes('🔵')).length

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI Code Review Report</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,'PingFang SC','Microsoft YaHei',sans-serif;background:#f5f5f5;color:#1a1a1a;line-height:1.6}
.container{max-width:900px;margin:0 auto;padding:40px 24px}
.header{background:#fff;border-radius:16px;padding:32px;margin-bottom:24px;box-shadow:0 2px 12px rgba(0,0,0,.06)}
.header h1{font-size:28px;font-weight:700;margin-bottom:8px}
.header .meta{font-size:14px;color:#888}
.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:24px}
.sum-card{background:#fff;border-radius:12px;padding:20px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.04)}
.sum-card .num{font-size:36px;font-weight:700}
.sum-card .label{font-size:13px;color:#888;margin-top:4px}
.sum-card.critical .num{color:#E74C3C}
.sum-card.high .num{color:#E67E22}
.sum-card.medium .num{color:#F39C12}
.sum-card.low .num{color:#3498DB}
.sum-card.total .num{color:#1a1a1a}
.issue-card{background:#fff;border-radius:12px;padding:20px 24px;margin-bottom:12px;box-shadow:0 1px 6px rgba(0,0,0,.04);border-left:4px solid #ccc}
.issue-head{display:flex;align-items:center;gap:12px;margin-bottom:10px}
.issue-severity{display:inline-block;padding:2px 10px;border-radius:4px;font-size:12px;font-weight:700;color:#fff;white-space:nowrap}
.issue-title{font-size:16px;font-weight:600}
.issue-meta{font-size:13px;color:#888;margin-bottom:8px}
.issue-section{font-size:14px;margin:6px 0}
.issue-code{background:#f8f8f8;border-radius:8px;padding:12px 16px;font-size:13px;font-family:'SFMono-Regular',Consolas,monospace;overflow-x:auto;margin:8px 0}
.verdict{background:#fff;border-radius:12px;padding:20px 24px;text-align:center;font-size:16px;font-weight:600;box-shadow:0 1px 6px rgba(0,0,0,.04)}
.verdict.good{color:#07C160}
.verdict.bad{color:#E74C3C}
.footer{text-align:center;margin-top:32px;font-size:13px;color:#bbb}
@media(max-width:600px){.container{padding:16px}.summary{grid-template-columns:repeat(3,1fr)}}
</style>
</head>
<body>
<div class="container">
<div class="header">
  <h1>🔍 AI Code Review Report</h1>
  <div class="meta">模式：${mode.toUpperCase()} · 路径：${paths.join(', ')} · ${new Date().toLocaleString('zh-CN')}</div>
</div>

<div class="summary">
  <div class="sum-card total"><div class="num">${total}</div><div class="label">总计问题</div></div>
  <div class="sum-card critical"><div class="num">${critical}</div><div class="label">🔴 严重</div></div>
  <div class="sum-card high"><div class="num">${high}</div><div class="label">🟠 高危</div></div>
  <div class="sum-card medium"><div class="num">${medium}</div><div class="label">🟡 中危</div></div>
  <div class="sum-card low"><div class="num">${low}</div><div class="label">🔵 低危</div></div>
</div>

${issueCards}

<div class="verdict ${critical > 0 ? 'bad' : 'good'}">
  ${critical > 0 ? '⚠️ 存在严重问题，建议修复后再提交' : '✅ 未发现严重问题，代码质量良好'}
</div>

<div class="footer">Generated by ai-review-cli · Powered by Claude API</div>
</div>
</body>
</html>`
}

interface ParsedIssue {
  file?: string
  severity: string
  title: string
  line?: string
  problem?: string
  fix?: string
  code?: string
}

function parseIssues(md: string): ParsedIssue[] {
  const issues: ParsedIssue[] = []
  const blocks = md.split(/(?=### )/g)
  for (const block of blocks) {
    const headerMatch = block.match(/###\s*([🔴🟠🟡🔵]?\s*(?:CRITICAL|HIGH|MEDIUM|LOW)?)\s*(.+)/)
    if (!headerMatch) continue
    const severity = headerMatch[1].trim()
    const title = headerMatch[2].trim()
    const lineMatch = block.match(/\*\*Line:\*\*\s*(.+)/i)
    const problemMatch = block.match(/\*\*Problem:\*\*\s*(.+)/i)
    const fixMatch = block.match(/\*\*Fix:\*\*\s*(.+)/i)
    const codeMatch = block.match(/```[\s\S]*?```/)
    const fileMatch = block.match(/\*\*File:\*\*\s*(.+)/i)
    issues.push({
      file: fileMatch?.[1]?.trim(),
      severity,
      title,
      line: lineMatch?.[1]?.trim(),
      problem: problemMatch?.[1]?.trim(),
      fix: fixMatch?.[1]?.trim(),
      code: codeMatch?.[0]?.replace(/```\w*\n?/g, '').replace(/```/g, '').trim(),
    })
  }
  return issues
}

function parseSummary(md: string) {
  const totalMatch = md.match(/Total issues:\s*(\d+)/i)
  const criticalMatch = md.match(/Critical:\s*(\d+)/i)
  const highMatch = md.match(/High:\s*(\d+)/i)
  const mediumMatch = md.match(/Medium:\s*(\d+)/i)
  const lowMatch = md.match(/Low:\s*(\d+)/i)
  return {
    total: totalMatch ? parseInt(totalMatch[1]) : 0,
    critical: criticalMatch ? parseInt(criticalMatch[1]) : 0,
    high: highMatch ? parseInt(highMatch[1]) : 0,
    medium: mediumMatch ? parseInt(mediumMatch[1]) : 0,
    low: lowMatch ? parseInt(lowMatch[1]) : 0,
  }
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
